service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-2
  httpApi:
    cors: true
package:
  excludeDevDependencies: true
functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
plugins:
  - serverless-esbuild
  - serverless-offline
# custom:
#   esbuild:
#     packager: yarn
#     external:
#       - "@apollo/server"
#       - "@as-integrations/aws-lambda"
#       - "graphql"
#     bundle: true
#     minify: false
#     sourcemap: true
#     exclude: ["aws-sdk"]
#     target: "node18"
#     define: { "require.resolve": undefined }
#     platform: "neutral"
#     concurrency: 10
