service: apollo-lambda
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  httpApi:
    cors: true
package:
  excludeDevDependencies: true
functions:
  graphql:
    handler: src/main.graphqlHandler
  graphql-local:
    handler: src/local.localHandler
plugins:
  - serverless-esbuild
  - serverless-offline
custom:
  serverless-offline:
    lambdaPort: 4000
    reloadHandler: true
